# Generated by Django 5.1.4 on 2025-01-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO store_collection(title) VALUES('collection1')
        """, """
        DELETE FROM store_collection WHERE title = 'collection1'
        """)
    ]
